version: '3'

volumes:
  pg_data_kittygram:
  kitty_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: evilboooy/kittygram_backend
    env_file: .env
    volumes:
      - kitty_static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: evilboooy/kittygram_frontend
    volumes:
      - kitty_static:/static
    command: cp -r /app/build/. /static/
  gateway:
    image: evilboooy/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - kitty_static:/static
      - media:/media
